/**
 * scripts/go-live.ts — take the local build live, on chain.
 *
 *   npm run go:live                          # inspect only; nothing is broadcast
 *   npm run go:live -- --apply               # broadcast the real confidential transfer
 *
 * ## What "live" means here
 *
 * Everything else in this repository is verifiable without funds: the 402 body,
 * the refusal codes, the ledger arithmetic, the proofs. One claim is not, and it
 * is the load-bearing one — that a payment can move between two accounts with
 * the amount never appearing in the clear. That claim needs a chain.
 *
 * So this runs the smallest honest sequence that tests it:
 *
 *   0. Read the live state and refuse to proceed unless the preconditions are
 *      really there — the mint carries the confidential extension and the
 *      destination is armed. Broadcasting against an unverified mint is how you
 *      get a public transfer while believing it was private.
 *   1. Create a source account with the confidential extension already allocated,
 *      configure it with a pubkey-validity proof, and enable confidential
 *      credits. Non-confidential credits stay *enabled* on the source, because
 *      the next step needs to mint into it publicly; the destination is the
 *      account that refuses plain transfers.
 *   2. Mint public tokens into the source and deposit them. The deposit is what
 *      turns a visible balance into a spendable confidential one.
 *   3. Transfer to the destination using the three proofs generated by
 *      `packages/onchain/src/proofs.ts` — the same prover `npm test` exercises,
 *      not a second implementation written for this script.
 *   4. Apply the destination's pending balance, so the run ends with the money
 *      moved rather than parked in a state only the sender can see.
 *   5. Re-read the destination and decrypt locally, to *report* what actually
 *      landed instead of asserting it.
 *
 * ## Why the instructions come from Veil's builders
 *
 * The token-2022 SDK also ships `getConfidentialTransferInstructionPlan`, which
 * builds the transfer *and generates its own proofs*. Substituting Veil's proofs
 * into that plan would leave the SDK's proofs in place as well, and a transaction
 * carrying two sets of proof instructions is a transaction whose offsets no
 * longer mean what either producer intended. So this script uses the SDK only
 * for the two things Veil does not implement — the deposit instruction and the
 * account decoder — and builds the confidential sequence from
 * `packages/onchain/src/index.ts`, whose instruction order and proof offsets are
 * already covered by the test suite.
 *
 * ## Reading state back
 *
 * The SDK's `getTokenDecoder()` decodes the account including its extension
 * payload, and `decryptConfidentialTransferBalance` decrypts the balance
 * ciphertexts with the local keys. A hand-computed byte offset is exactly the
 * kind of thing that is right in a test fixture and wrong against live data.
 */

import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

import { DATA_DIR, clusterTag } from './lib.ts';

import { getCreateAccountInstruction } from '@solana-program/system';
import {
  appendTransactionMessageInstructions,
  createKeyPairSignerFromPrivateKeyBytes,
  createSolanaRpc,
  generateKeyPairSigner,
  getBase58Encoder,
  getBase64EncodedWireTransaction,
  getSignatureFromTransaction,
  isFullySignedTransaction,
  isSome,
  pipe,
  createTransactionMessage,
  setTransactionMessageFeePayerSigner,
  setTransactionMessageLifetimeUsingBlockhash,
  signTransactionMessageWithSigners,
  type Address,
  type Instruction,
} from '@solana/kit';
import {
  getApproveConfidentialTransferAccountInstruction,
  getConfidentialDepositInstruction,
  getEnableConfidentialCreditsInstruction,
  getMintToInstruction,
  getTokenDecoder,
  TOKEN_2022_PROGRAM_ADDRESS,
} from '@solana-program/token-2022';
import { decryptConfidentialTransferBalance } from '@solana-program/token-2022/confidential';
import {
  RECORD_CHUNK_SIZE_POST_INITIALIZE,
  RECORD_META_DATA_SIZE,
  RECORD_PROGRAM_ADDRESS,
  getCloseAccountInstruction as getCloseRecordAccountInstruction,
  getInitializeInstruction as getInitializeRecordInstruction,
  getRecordSize,
  getWriteInstruction,
} from '@solana-program/record';
import {
  closeContextStateProof,
  verifyBatchedGroupedCiphertext3HandlesValidity,
  verifyBatchedRangeProofU128,
  verifyCiphertextCommitmentEquality,
} from '@solana-program/zk-elgamal-proof';
import { ElGamalCiphertext, ElGamalPubkey } from '@solana/zk-sdk';

import {
  buildApplyPendingBalance,
  buildConfidentialTransfer,
  buildConfigureAccount,
  buildCreatePaymentAccount,
  confidentialAccountSpace,
} from '../packages/onchain/src/index.ts';
import {
  buildPubkeyValidityProof,
  buildTransferProofs,
  confidentialDerivationMessage,
  confidentialKeysFrom,
  encryptBalance,
  PROOF_OFFSET_IMMEDIATELY_PRECEDING,
} from '../packages/onchain/src/proofs.ts';

/** The keys type, taken from the function that produces it rather than guessed. */
type ConfidentialKeys = Awaited<ReturnType<typeof confidentialKeysFrom>>;
import { PoolLedger } from '../packages/derive/src/index.ts';
import { PLACEHOLDER_MINT } from '../packages/x402-core/src/index.ts';
import {
  KEYS_DIR,
  MINT_PATH,
  decodeSecret,
  optionsFromEnv,
  readJSON,
  relative,
  saveJSON,
  table,
} from './lib.ts';

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

const options = optionsFromEnv(process.argv.slice(2));
const apply = process.argv.includes('--apply');

const rpcUrl = options.rpcUrl;
if (!rpcUrl) {
  process.stderr.write(
    'go:live needs an RPC endpoint, because the point of it is to reach a chain.\n\n' +
      '  VEIL_RPC_URL=https://api.testnet.solana.com VEIL_NETWORK=solana:testnet npm run go:live\n\n' +
      'Without --apply it reads and reports only. Nothing is broadcast either way\n' +
      'until you pass --apply.\n',
  );
  process.exit(1);
}

const rpc = createSolanaRpc(rpcUrl);

/** 0.049 tokens at 6 decimals — the demo's ticket size. */
const AMOUNT = 49_000n;
/** The confidential-extension cap this project configures everywhere. */
const MAX_PENDING_CREDIT_COUNTER = 65_535n;

let failed = 0;

/**
 * A gap between transactions.
 *
 * The free public RPC answers `429` under a burst, and this script sends eight
 * transactions in a row. Waiting is cheaper than retrying, and it makes the run
 * reproducible on the endpoint everyone has access to rather than only on a paid
 * one.
 */
const PAUSE_BETWEEN_TXS_MS = 1_200;

function step(n: string, title: string): void {
  process.stdout.write(`\n${n} · ${title}\n`);
}

function ok(label: string, detail = ''): void {
  process.stdout.write(`  ok    ${label}${detail ? `  ${detail}` : ''}\n`);
}

function stop(label: string, detail = ''): void {
  failed += 1;
  process.stdout.write(`  STOP  ${label}${detail ? `  ${detail}` : ''}\n`);
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Retry an operation that only *reads* from the chain.
 *
 * This is deliberately not applied to broadcasting. A retried read is free and
 * idempotent; a retried send after an ambiguous failure is how a payment gets
 * made twice. So the split is: reads retry, sends are attempted once with their
 * own bounded retry around the *transport* only.
 */
async function retryRead<T>(label: string, fn: () => Promise<T>): Promise<T> {
  const MAX_ATTEMPTS = 5;
  let lastError: unknown = new Error(`${label} failed`);
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error;
      if (!isTransient(error) || attempt === MAX_ATTEMPTS) throw error;
      process.stdout.write(
        `  retry ${label} — attempt ${attempt + 1}/${MAX_ATTEMPTS}\n`,
      );
      await sleep(1_000 * 2 ** (attempt - 1) + Math.floor(Math.random() * 500));
    }
  }
  throw lastError;
}

/**
 * A rate-limited public RPC answers `429` and drops connections under load.
 * Those are worth retrying; a rejected instruction is not, and retrying it just
 * costs a second preflight failure.
 */
function isTransient(error: unknown): boolean {
  const text = String((error as { message?: string })?.message ?? error);
  return (
    text.includes('429') ||
    text.includes('Too Many Requests') ||
    text.includes('fetch failed') ||
    text.includes('ECONNRESET') ||
    text.includes('ETIMEDOUT') ||
    text.includes('socket hang up') ||
    text.includes('Blockhash not found')
  );
}

/**
 * Sign and send one transaction, then wait for it to be confirmed.
 *
 * Confirmation is not optional on this path: the next step reads the account the
 * previous step wrote, so a `sendTransaction` that has not landed yet would make
 * this script decrypt a balance that does not exist and report the wrong thing.
 * The signature is polled rather than subscribed because a public RPC's
 * websocket endpoint is the flakier of its two interfaces.
 */
async function send(label: string, instructions: readonly Instruction[]): Promise<string> {
  if (instructions.length === 0) throw new Error(`${label}: no instructions to send`);

  /**
   * Attempts are generous because the free public RPC enforces a per-second
   * request limit and this run sends eight transactions. Five attempts with a
   * one-second base ran out during development; the limiter clears in tens of
   * seconds, so the ceiling here is set to outlast it rather than to fail fast.
   */
  const MAX_SEND_ATTEMPTS = 8;
  let signature: string | undefined;
  let lastError: unknown = new Error('send failed');

  for (let attempt = 1; attempt <= MAX_SEND_ATTEMPTS; attempt++) {
    try {
      const { value: lifetime } = await rpc.getLatestBlockhash().send();
      const message = pipe(
        createTransactionMessage({ version: 0 }),
        (tx) => setTransactionMessageFeePayerSigner(payer, tx),
        (tx) => setTransactionMessageLifetimeUsingBlockhash(lifetime, tx),
        (tx) => appendTransactionMessageInstructions(instructions, tx),
      );
      const signed = await signTransactionMessageWithSigners(message);
      if (!isFullySignedTransaction(signed)) {
        throw new Error(`${label}: the transaction is not fully signed`);
      }
      signature = getSignatureFromTransaction(signed);
      await rpc
        .sendTransaction(getBase64EncodedWireTransaction(signed), {
          encoding: 'base64',
          preflightCommitment: 'confirmed',
        })
        .send();
      break;
    } catch (error) {
      lastError = error;
      if (!isTransient(error) || attempt === MAX_SEND_ATTEMPTS) throw error;
      const wait = Math.min(20_000, 2_000 * 2 ** (attempt - 1)) + Math.floor(Math.random() * 500);
      process.stdout.write(
        `  retry ${label} — attempt ${attempt + 1}/${MAX_SEND_ATTEMPTS} in ${Math.round(wait / 100) / 10}s\n`,
      );
      await sleep(wait);
    }
  }
  if (!signature) throw lastError;

  const CONFIRM_TIMEOUT_MS = 60_000;
  const deadline = Date.now() + CONFIRM_TIMEOUT_MS;
  while (Date.now() < deadline) {
    const { value } = await rpc
      .getSignatureStatuses([signature as never])
      .send();
    const status = value[0];
    if (status?.err) {
      throw new Error(`${label}: the transaction failed on chain — ${JSON.stringify(status.err)}`);
    }
    if (status?.confirmationStatus === 'confirmed' || status?.confirmationStatus === 'finalized') {
      ok(label, `${instructions.length} ix · ${signature}`);
      return signature;
    }
    // Polled slowly on purpose: each poll is a request against the same
    // per-second budget as the transactions themselves, so a tight poll loop
    // starves the next send. Confirmation normally lands inside one interval.
    await sleep(2_000);
  }
  throw new Error(`${label}: ${signature} was not confirmed within ${CONFIRM_TIMEOUT_MS / 1000}s`);
}

// ---------------------------------------------------------------------------
// 0 · Preconditions, read from the chain
// ---------------------------------------------------------------------------

step('0', 'Preconditions, read from the chain');

/**
 * Which mint to run against.
 *
 * `optionsFromEnv` falls back to a placeholder address, which is the right
 * default for the offline scripts but exactly the wrong one here: this script
 * exists to reach a chain, so a placeholder would send it looking for an account
 * that was never meant to exist. When no mint was passed explicitly, the mint
 * this project actually created and verified is read from `data/mint.json`.
 */
let mintRecord: { mint?: string } = {};
try {
  mintRecord = await readJSON<{ mint?: string }>(MINT_PATH, {});
} catch {
  mintRecord = {};
}

const mint = (
  options.mint !== PLACEHOLDER_MINT ? options.mint : (mintRecord.mint ?? options.mint)
) as Address;

if (options.mint === PLACEHOLDER_MINT) {
  if (!mintRecord.mint) {
    stop(
      'no mint was passed and no mint is recorded',
      `pass --mint=<address>, or run \`npm run setup:devnet\` to create one (${relative(MINT_PATH)} is absent)`,
    );
    process.exit(1);
  }
  ok('no --mint given; using the recorded one', `${mint} from ${relative(MINT_PATH)}`);
}

const mintInfo = await rpc.getAccountInfo(mint, { encoding: 'base64' }).send();
if (!mintInfo.value) {
  stop('the mint does not exist on this cluster', mint);
  process.exit(1);
}
ok('the mint exists', mint);

const mintData = Buffer.from(mintInfo.value.data[0], 'base64');
/**
 * Walk the mint's TLV extension table.
 *
 * The base mint is 82 bytes; the account-type tag occupies byte 165, so the
 * extension header starts at 166. That off-by-one is the bug a previous version
 * of this project shipped — the reader started at 165 and read the account-type
 * byte as an extension type, which made a mint with the confidential extension
 * report as having none.
 */
const MINT_TLV_START = 166;
const extensionTypes: number[] = [];
{
  let cursor = MINT_TLV_START;
  while (cursor + 4 <= mintData.length) {
    const type = mintData.readUInt16LE(cursor);
    const length = mintData.readUInt16LE(cursor + 2);
    if (type === 0) break;
    extensionTypes.push(type);
    cursor += 4 + length;
  }
}
/**
 * `ConfidentialTransferMint` is extension type 4 in Token-2022's enum — this is
 * worth stating because 10 is `InterestBearingConfig`, and checking for 10 makes
 * a correctly-configured mint look unconfigured. `ConfidentialTransferAccount`,
 * the per-account counterpart, is 5.
 */
const EXT_CONFIDENTIAL_TRANSFER_MINT = 4;
if (!extensionTypes.includes(EXT_CONFIDENTIAL_TRANSFER_MINT)) {
  stop(
    'the mint does not carry the ConfidentialTransferMint extension',
    `extensions seen: ${extensionTypes.join(', ') || 'none'}`,
  );
  process.exit(1);
}
ok(
  'the mint carries the confidential extension',
  `type ${EXT_CONFIDENTIAL_TRANSFER_MINT} among [${extensionTypes.join(', ')}]`,
);

const rawLedger = await readJSON<unknown[]>(options.ledgerPath, []);
const ledger = PoolLedger.fromJSON(rawLedger);
const poolAccounts = ledger.allFor();
ok(
  'the pool ledger is loaded',
  `${poolAccounts.length} accounts from ${relative(options.ledgerPath)}`,
);

/**
 * Destinations this script has already paid into.
 *
 * Kept here rather than in the pool ledger on purpose. The ledger is the server's
 * record of *payments it quoted* — an alias, a reserved slot, a settlement — and
 * a script that reaches around the quote flow to stamp `consumedBy` on a slot
 * would be writing a reservation it never made. This file is go-live's own
 * bookkeeping: which pool accounts it has funded, and with what, so a re-run does
 * not try to spend into a destination that already holds a balance. That matters,
 * because the safety check below refuses a non-empty destination, and after the
 * first successful run *every* reused destination would trip it.
 */
const RUNS_PATH = join(DATA_DIR, `go-live${clusterTag(rpcUrl, options.network)}.json`);

interface GoLiveRuns {
  readonly runs: {
    readonly destination: string;
    readonly amount: string;
    readonly signature: string;
    readonly at: string;
  }[];
}

const priorRuns = await readJSON<GoLiveRuns>(RUNS_PATH, { runs: [] });
const funded = new Set(priorRuns.runs.map((run) => run.destination));

const destinationEntry = poolAccounts.find(
  (e) => e.armed && !e.consumedBy && !funded.has(e.address),
);
if (!destinationEntry) {
  stop(
    'no armed, unconsumed account in the pool that has not already been paid',
    `run \`npm run setup:devnet\` to add more, or clear ${relative(RUNS_PATH)}`,
  );
  process.exit(1);
}

const destination = destinationEntry.address as Address;
const destinationInfo = await rpc.getAccountInfo(destination, { encoding: 'base64' }).send();
if (!destinationInfo.value) {
  stop('the destination account is not on chain', destination);
  process.exit(1);
}
ok('an armed destination exists on chain', `${destination} (slot ${destinationEntry.slot})`);

// Decode through the SDK's own decoder: the extension payload is a real field,
// not a byte offset this script has to guess at.
const tokenDecoder = getTokenDecoder();
const decodedDestination = tokenDecoder.decode(
  Buffer.from(destinationInfo.value.data[0], 'base64'),
);
const destinationExtensions = isSome(decodedDestination.extensions)
  ? decodedDestination.extensions.value
  : [];
const destinationExtension = destinationExtensions.find(
  (e) => e.__kind === 'ConfidentialTransferAccount',
);
if (!destinationExtension || destinationExtension.__kind !== 'ConfidentialTransferAccount') {
  stop('the destination has no ConfidentialTransferAccount extension', destination);
  process.exit(1);
}
if (!destinationExtension.allowConfidentialCredits) {
  stop('the destination does not accept confidential credits', destination);
  process.exit(1);
}
if (destinationExtension.allowNonConfidentialCredits) {
  // Not fatal, but worth naming: the pool is armed to *refuse* plain transfers,
  // which is what turns a failed proof into an on-chain error instead of a
  // silent public payment.
  process.stdout.write(
    `  note  the destination still accepts non-confidential credits; a failed\n` +
      `        proof would settle as a visible transfer on this account\n`,
  );
}
ok(
  'the destination accepts confidential credits',
  `allowNonConfidentialCredits=${destinationExtension.allowNonConfidentialCredits}`,
);

/**
 * The mint was created with `autoApproveNewAccounts: false`, which is the safer
 * setting — it means an account has to be vouched for by the mint authority
 * before it can hold a confidential balance, so a stranger cannot create one and
 * quietly receive private payments. The cost of that setting is that approval is
 * a *required* step, and an unapproved account fails `Deposit` and `Transfer`
 * with a bare `custom program error: 0x18` that names nothing useful. So it is
 * checked here and performed below rather than discovered from a program error.
 */
const destinationApproved = destinationExtension.approved;
if (destinationApproved) {
  ok('the destination is approved for confidential transfers');
} else {
  process.stdout.write(
    '  note  the destination is not yet approved for confidential transfers;\n' +
      '        the mint authority approves it before anything is deposited\n',
  );
}

// ---------------------------------------------------------------------------
// 1 · The payer, and its confidential keys
// ---------------------------------------------------------------------------

step('1', 'The payer and its confidential keys');

const payerSeed = decodeSecret(await readFile(join(KEYS_DIR, 'payer.json'), 'utf8'));
if (!payerSeed) {
  stop(`${relative(join(KEYS_DIR, 'payer.json'))} is not a valid keypair`);
  process.exit(1);
}
const payer = await createKeyPairSignerFromPrivateKeyBytes(payerSeed);

const balance = await rpc.getBalance(payer.address).send();
const sol = Number(balance.value) / 1e9;
ok('the payer key loaded', payer.address);
ok('the payer holds SOL', `${sol.toFixed(4)} SOL`);

/**
 * Fees, plus rent for one token account, plus the confidential reallocation.
 * 0.02 SOL is a generous floor that still catches a payer with nothing in it.
 */
const MIN_SOL = 0.02;
if (sol < MIN_SOL) {
  stop(
    `the payer holds ${sol.toFixed(4)} SOL, below the ${MIN_SOL} SOL this needs`,
    'fund it, then re-run',
  );
  process.exit(1);
}

/**
 * The payer's confidential keys.
 *
 * Derived exactly as `setup-devnet` derives the pool's keys — one signature over
 * the fixed derivation message, reused across every account the payer owns. That
 * is not a shortcut: it is what makes step 4 possible at all. Applying the
 * destination's pending balance requires the *destination's* ElGamal secret, and
 * the pool's accounts share the payer's derivation, so the same keys decrypt
 * them. If the pool were configured with per-account keys, this script could not
 * finish the transfer it starts.
 */
async function signDerivation(seed: Uint8Array): Promise<Uint8Array> {
  const { createPrivateKey, sign } = await import('node:crypto');
  const PKCS8_ED25519_PREFIX = Buffer.from('302e020100300506032b657004220420', 'hex');
  const key = createPrivateKey({
    key: Buffer.concat([PKCS8_ED25519_PREFIX, Buffer.from(seed)]),
    format: 'der',
    type: 'pkcs8',
  });
  return new Uint8Array(sign(null, Buffer.from(confidentialDerivationMessage()), key));
}

let keys: ConfidentialKeys;
try {
  keys = await confidentialKeysFrom(() => signDerivation(payerSeed));
} catch (error) {
  stop('the confidential keys could not be derived', (error as Error).message);
  process.exit(1);
}
const sourceElgamalKeypair = keys.elgamal();
const aesKey = keys.ae();
ok('confidential keys derived locally', `ElGamal pubkey ${sourceElgamalKeypair.pubkey().toBytes().length}B`);

/**
 * The destination's ElGamal public key, read from its on-chain extension. The
 * stored form is base58 (it is an `Address`), so it is decoded to the 32 raw
 * bytes the prover takes.
 */
const destinationPubkey = ElGamalPubkey.fromBytes(
  new Uint8Array(getBase58Encoder().encode(destinationExtension.elgamalPubkey)),
);
ok('the destination ElGamal key decoded from live state', destinationExtension.elgamalPubkey);

// ---------------------------------------------------------------------------
// The source account, and what this run would cost
// ---------------------------------------------------------------------------

/**
 * A fresh source account per run.
 *
 * An associated token account will not do: a standard ATA is 165 bytes, and the
 * confidential extension needs the account to have been allocated with room for
 * it. Token-2022 can reallocate, but creating the account at the right size is
 * the shorter path and removes a whole class of "the extension was not there
 * yet" failures. The cost is one rent-exempt account, which is why this is
 * reported before it is spent.
 */
const source = await generateKeyPairSigner();
const sourceRent = await rpc
  .getMinimumBalanceForRentExemption(BigInt(confidentialAccountSpace()))
  .send();
const rentSol = Number(sourceRent) / 1e9;

if (!apply) {
  /**
   * Decrypt the destination here, before anything is spent.
   *
   * The final step of `--apply` depends on two things that are cheap to check
   * and expensive to discover late: that the SDK's decoder accepts this account
   * shape, and that the payer's derived keys are the ones the account was
   * configured with. If either is wrong, the run would broadcast a real transfer
   * and then be unable to read the result — the money would move and the script
   * would report a failure. So it is proven on the read-only path first.
   */
  const decrypted = decryptConfidentialTransferBalance({
    tokenAccount: decodedDestination,
    elgamalSecretKey: keys.elgamal().secret(),
    aesKey: keys.ae(),
  });
  ok(
    'the destination decrypts locally',
    `available ${decrypted.availableBalance}, pending ${decrypted.pendingBalance}, ` +
      `credits ${decrypted.actualPendingBalanceCreditCounter}/${decrypted.maximumPendingBalanceCreditCounter}`,
  );
  if (decrypted.availableBalance !== 0n || decrypted.pendingBalance !== 0n) {
    stop(
      'the destination is not empty',
      `available ${decrypted.availableBalance}, pending ${decrypted.pendingBalance} — ` +
        'this run assumes a fresh destination, and would overwrite a real balance',
    );
    process.exit(1);
  }

  process.stdout.write(
    [
      '',
      '  Read-only pass. Nothing was broadcast.',
      '',
      '  What --apply would do:',
      `    1. create + configure the source account ${source.address}`,
      `       ${confidentialAccountSpace()} B, ${rentSol.toFixed(6)} SOL rent`,
      '       with a pubkey-validity proof (generated here, from the local key)',
      `    2. approve the source${destinationApproved ? '' : ' and the destination'} —\n` +
      '       autoApproveNewAccounts is off, so the mint authority vouches for each',
      '    3. mint + deposit the amount public-side, then confidential-side:',
      `       0.049 tokens (${AMOUNT} atomic units) at ${options.decimals} decimals`,
      `    4. transfer ${AMOUNT} confidentially to ${destination}`,
      '       with 3 proofs from packages/onchain/src/proofs.ts',
      '    5. apply the pending balance on the destination',
      '    6. re-read and decrypt the destination, to report what landed',
      '',
      '  Every precondition above was read from the chain, not assumed.',
      '  Re-run with --apply to broadcast.',
      '',
    ].join('\n'),
  );
  process.exit(failed === 0 ? 0 : 1);
}

// ---------------------------------------------------------------------------
// 2 · Create and configure the source
// ---------------------------------------------------------------------------

step('2', 'Create and configure the source account');

/**
 * Order matters, and it is the order `setup-devnet` proved against the live
 * program: allocate the account, then the pubkey-validity proof, then the
 * configure instruction that refers to it by offset, then enable confidential
 * credits.
 *
 * `disableNonConfidentialCredits` is deliberately omitted. The destination in
 * this pool refuses plain credits; the source must accept them, because the next
 * step mints into it publicly before depositing.
 */
await send('created + configured the source, with a local pubkey proof', [
  ...buildCreatePaymentAccount({
    payer,
    account: source,
    mint,
    owner: payer.address,
    lamports: sourceRent,
  }),
  buildPubkeyValidityProof(keys),
  buildConfigureAccount({
    token: source.address,
    mint,
    authority: payer,
    proofInstructionOffset: PROOF_OFFSET_IMMEDIATELY_PRECEDING,
    maximumPendingBalanceCreditCounter: MAX_PENDING_CREDIT_COUNTER,
    decryptableZeroBalance: encryptBalance(keys, 0n),
  }),
  getEnableConfidentialCreditsInstruction({ token: source.address, authority: payer }),
  // The mint authority vouches for this account. Without it the deposit below
  // fails, because `autoApproveNewAccounts` is false on this mint.
  getApproveConfidentialTransferAccountInstruction({
    token: source.address,
    mint,
    authority: payer,
  }),
]);

if (!destinationApproved) {
  await send('approved the destination for confidential transfers', [
    getApproveConfidentialTransferAccountInstruction({
      token: destination,
      mint,
      authority: payer,
    }),
  ]);
}

// ---------------------------------------------------------------------------
// 3 · Fund it publicly, then deposit
// ---------------------------------------------------------------------------

step('3', 'Mint public tokens, then deposit them');

await send('minted the amount publicly', [
  getMintToInstruction({
    mint,
    token: source.address,
    mintAuthority: payer,
    amount: AMOUNT,
  }),
]);

// The deposit is the step that turns a visible balance into a confidential one.
// A plain amount goes in; the account's encrypted balance becomes that amount.
await send('deposited into the confidential balance', [
  getConfidentialDepositInstruction({
    token: source.address,
    mint,
    authority: payer,
    amount: AMOUNT,
    decimals: options.decimals,
  }),
]);

/**
 * Move the deposit from pending to available.
 *
 * A deposit credits the *pending* balance, not the available one. Token-2022
 * separates the two on purpose: value that arrived while the owner was not
 * looking cannot be spent until the owner has acknowledged it. So an account can
 * hold 0.049 tokens, decrypt them, and still have nothing spendable — which is
 * exactly what the first run of this script discovered, one step later, with an
 * available balance of zero and a pending balance of 49000.
 */
const depositedInfo = await rpc.getAccountInfo(source.address, { encoding: 'base64' }).send();
if (!depositedInfo.value) throw new Error('the source account vanished after the deposit');
const depositedBalance = decryptConfidentialTransferBalance({
  tokenAccount: tokenDecoder.decode(Buffer.from(depositedInfo.value.data[0], 'base64')),
  elgamalSecretKey: sourceElgamalKeypair.secret(),
  aesKey,
});
ok(
  'the deposit landed in the pending balance',
  `pending ${depositedBalance.pendingBalance}, available ${depositedBalance.availableBalance}`,
);

await send('applied the deposit to the available balance', [
  buildApplyPendingBalance({
    token: source.address,
    authority: payer,
    expectedPendingBalanceCreditCounter: depositedBalance.expectedPendingBalanceCreditCounter,
    newDecryptableAvailableBalance: encryptBalance(
      keys,
      depositedBalance.availableBalance + depositedBalance.pendingBalance,
    ),
  }),
]);

// ---------------------------------------------------------------------------
// 4 · The confidential transfer, proved by Veil
// ---------------------------------------------------------------------------

step('4', "Transfer confidentially, with Veil's proofs generated locally");

const armedSource = await rpc.getAccountInfo(source.address, { encoding: 'base64' }).send();
if (!armedSource.value) throw new Error('the source account vanished after the deposit');
const decodedSource = tokenDecoder.decode(Buffer.from(armedSource.value.data[0], 'base64'));
const sourceExtensions = isSome(decodedSource.extensions) ? decodedSource.extensions.value : [];
const sourceExtension = sourceExtensions.find(
  (e) => e.__kind === 'ConfidentialTransferAccount',
);
if (!sourceExtension || sourceExtension.__kind !== 'ConfidentialTransferAccount') {
  throw new Error('the source lost its confidential extension after the deposit');
}

// Decrypt locally, so the amount moved is a number this run knows rather than
// one it assumed. The ciphertext is public — it is on the account — but the
// plaintext behind it exists only here.
const sourceBefore = decryptConfidentialTransferBalance({
  tokenAccount: decodedSource,
  elgamalSecretKey: sourceElgamalKeypair.secret(),
  aesKey,
});
ok(
  'the source balance was decrypted locally',
  `available ${sourceBefore.availableBalance}, pending ${sourceBefore.pendingBalance}`,
);

if (sourceBefore.availableBalance !== AMOUNT) {
  // The equality proof commits to "new balance = the on-chain balance minus this
  // transfer". Proving against a balance the chain does not hold fails, so this
  // is checked rather than assumed — a deposit that silently deposited a
  // different amount would otherwise surface as an opaque program error.
  throw new Error(
    `the source available balance is ${sourceBefore.availableBalance}, expected ${AMOUNT}; ` +
      'the equality proof would commit to the wrong value',
  );
}

// The 64-byte commitment||handle the prover takes, straight from the decoded
// extension — no byte-offset arithmetic.
const balanceCiphertext = new Uint8Array(sourceExtension.availableBalance);
const parsedBalance = ElGamalCiphertext.fromBytes(balanceCiphertext);
if (!parsedBalance) {
  throw new Error(
    `the decoded available balance is not a valid ElGamal ciphertext (${balanceCiphertext.length} bytes)`,
  );
}
ok('the on-chain ciphertext was decoded from live state', `${balanceCiphertext.length}B`);

const proofs = buildTransferProofs({
  keys,
  sourceAvailableBalance: sourceBefore.availableBalance,
  sourceAvailableBalanceCiphertext: parsedBalance,
  amount: AMOUNT,
  destinationPubkey,
});

const proofBytes = proofs.proofBytes;
const proofTotal = proofBytes.equality.length + proofBytes.ciphertextValidity.length + proofBytes.range.length;
ok(
  'three proofs generated locally',
  `${proofBytes.equality.length} + ${proofBytes.ciphertextValidity.length} + ` +
    `${proofBytes.range.length} = ${proofTotal} B`,
);
ok(
  'the new source balance is the old one minus the amount',
  `${sourceBefore.availableBalance} − ${AMOUNT} = ${proofs.newAvailableBalance}`,
);

/**
 * Verify the proofs into context-state accounts, then transfer against them.
 *
 * This is the shape the arithmetic forces. 1867 bytes of proof do not fit in a
 * 1232-byte transaction, and the offset form of the transfer requires all three
 * verification instructions to be *in the same transaction* — so a transfer of
 * this size can never work that way. Verifying into context-state accounts moves
 * the proofs out of the transfer's transaction entirely; the transfer then names
 * three accounts and sets every offset to `0`, the wire value for "read the
 * proof from the account".
 */
const recordKeys = {
  equality: await generateKeyPairSigner(),
  ciphertextValidity: await generateKeyPairSigner(),
  range: await generateKeyPairSigner(),
};

/**
 * Each proof gets its own transaction.
 *
 * The largest payload is 1001 bytes and each verification carries an account
 * creation and a rent check, so combining them would put the transaction back
 * over the ceiling that made this necessary.
 */
/**
 * Verify one proof into a context account, retrying only the read-only build.
 *
 * The SDK's verify action queries the chain for the context account's rent before
 * it can build the instructions, and that read is what a public RPC's rate
 * limiter hits first. The query is retried; the send is not wrapped in the same
 * loop, because re-running it after an ambiguous failure would try to create the
 * same context account a second time.
 */
async function verifyIntoContext(
  label: string,
  verify: typeof verifyBatchedRangeProofU128,
  contextAccount: Awaited<ReturnType<typeof generateKeyPairSigner>>,
  proofData: Parameters<typeof verifyBatchedRangeProofU128>[0]['proofData'],
): Promise<void> {
  const instructions = await retryRead(`build the verification for ${label}`, () =>
    verify({
      rpc,
      payer,
      proofData,
      contextState: { contextAccount, authority: payer.address },
    }),
  );
  await send(label, instructions);
  await sleep(PAUSE_BETWEEN_TXS_MS);
}

await verifyIntoContext(
  'verified the equality proof into a context account',
  verifyCiphertextCommitmentEquality,
  recordKeys.equality,
  proofBytes.equality,
);

await verifyIntoContext(
  'verified the ciphertext-validity proof into a context account',
  verifyBatchedGroupedCiphertext3HandlesValidity,
  recordKeys.ciphertextValidity,
  proofBytes.ciphertextValidity,
);

/**
 * The range proof is the one that does not fit — in anything.
 *
 * It is 1000 bytes. Embedded as instruction data, its verification transaction
 * comes to 1816 bytes against the same 1232-byte ceiling, so unlike the other two
 * it cannot be carried inline even in a transaction of its own. Token-2022's
 * answer is a *record account*: the proof is written into an account of its own,
 * a chunk per transaction, and the verification instruction then names that
 * account instead of embedding the bytes. The transaction shrinks to a few
 * hundred bytes because account data does not count against a transaction's size
 * — only the account's 32-byte address does.
 *
 * This is the same mechanism the SDK's `...WithRecord` helpers use. It is built
 * by hand here rather than delegated, because the whole point of this script is
 * that the proof bytes are Veil's.
 */
const rangeRecord = await generateKeyPairSigner();
const rangeRecordSize = getRecordSize(proofBytes.range.length);
const rangeRecordRent = await retryRead('read the record account rent', () =>
  rpc.getMinimumBalanceForRentExemption(rangeRecordSize).send(),
);

await send(`created a ${rangeRecordSize}B record account for the range proof`, [
  getCreateAccountInstruction({
    payer,
    newAccount: rangeRecord,
    lamports: rangeRecordRent,
    space: rangeRecordSize,
    programAddress: RECORD_PROGRAM_ADDRESS,
  }),
  getInitializeRecordInstruction({ recordAccount: rangeRecord.address, authority: payer }),
]);
await sleep(PAUSE_BETWEEN_TXS_MS);

// One chunk per transaction: a full 917-byte chunk plus another instruction would
// put the transaction back over the limit, which is why the chunk size is what it
// is.
const chunks: Uint8Array[] = [];
for (let offset = 0; offset < proofBytes.range.length; offset += RECORD_CHUNK_SIZE_POST_INITIALIZE) {
  chunks.push(proofBytes.range.slice(offset, offset + RECORD_CHUNK_SIZE_POST_INITIALIZE));
}
for (const [index, chunk] of chunks.entries()) {
  const offset = index * RECORD_CHUNK_SIZE_POST_INITIALIZE;
  await send(
    `wrote range-proof bytes ${offset}..${offset + chunk.length} into the record account`,
    [
      getWriteInstruction({
        recordAccount: rangeRecord.address,
        authority: payer,
        offset,
        data: chunk,
      }),
    ],
  );
  await sleep(PAUSE_BETWEEN_TXS_MS);
}

// The offset is `RECORD_META_DATA_SIZE` (33) and not 0, because a record account
// carries a 33-byte header and the proof payload begins after it. `Write`'s own
// offset is payload-relative and the program adds the header itself, which is why
// the writes above start at 0 while this read starts at 33 — an asymmetry worth
// naming, because reading at 0 fails with `proof verification failed:
// ProofContext`, which names neither the offset nor the record.
await verifyIntoContext(
  'verified the range proof into a context account, reading it from the record',
  verifyBatchedRangeProofU128,
  recordKeys.range,
  // `RECORD_META_DATA_SIZE` is a bigint and the proof-data argument takes a
  // number, so it is converted — the same conversion the SDK's own record path
  // performs. 33 bytes cannot lose precision going through a number.
  { account: rangeRecord.address, offset: Number(RECORD_META_DATA_SIZE) },
);

// The record account is scaffolding too, and it is the largest of the temporary
// accounts. Closing it returns its rent to the payer.
await send('closed the record account', [
  getCloseRecordAccountInstruction({
    recordAccount: rangeRecord.address,
    authority: payer,
    receiver: payer.address,
  }),
]);
await sleep(PAUSE_BETWEEN_TXS_MS);

const transferSignature = await send('transferred confidentially', [
  ...buildConfidentialTransfer({
    sourceToken: source.address,
    mint,
    destinationToken: destination,
    authority: payer,
    newSourceDecryptableAvailableBalance: proofs.newSourceDecryptableAvailableBalance,
    transferAmountAuditorCiphertextLo: proofs.auditorCiphertextLo,
    transferAmountAuditorCiphertextHi: proofs.auditorCiphertextHi,
    proofRecords: {
      equality: recordKeys.equality.address,
      ciphertextValidity: recordKeys.ciphertextValidity.address,
      range: recordKeys.range.address,
    },
  }),
]);

/**
 * Reclaim the context accounts' rent.
 *
 * They are scaffolding: a proof is verified into one so a *later* transaction can
 * refer to it, and once the transfer has read it the account has no further use.
 * Leaving them behind would leak a rent-exempt balance per payment, which on a
 * real rail is a slow leak proportional to volume. Closing is also what proves
 * the accounts really were plain context state rather than something the transfer
 * still depended on.
 */
await send('closed the three context accounts', [
  closeContextStateProof({
    contextState: recordKeys.equality.address,
    authority: payer,
    destination: payer.address,
  }),
  closeContextStateProof({
    contextState: recordKeys.ciphertextValidity.address,
    authority: payer,
    destination: payer.address,
  }),
  closeContextStateProof({
    contextState: recordKeys.range.address,
    authority: payer,
    destination: payer.address,
  }),
]);

// ---------------------------------------------------------------------------
// 5 · Apply the destination's pending balance
// ---------------------------------------------------------------------------

step('5', 'Apply the pending balance on the destination');

const creditedInfo = await rpc.getAccountInfo(destination, { encoding: 'base64' }).send();
if (!creditedInfo.value) throw new Error('the destination vanished after the transfer');
const decodedCredited = tokenDecoder.decode(Buffer.from(creditedInfo.value.data[0], 'base64'));

const destinationBefore = decryptConfidentialTransferBalance({
  tokenAccount: decodedCredited,
  elgamalSecretKey: sourceElgamalKeypair.secret(),
  aesKey,
});
ok(
  'the destination received a pending credit',
  `pending ${destinationBefore.pendingBalance}, available ${destinationBefore.availableBalance}`,
);
if (destinationBefore.pendingBalance !== AMOUNT) {
  throw new Error(
    `the destination pending balance is ${destinationBefore.pendingBalance}, expected ${AMOUNT}`,
  );
}

const newAvailable = destinationBefore.availableBalance + destinationBefore.pendingBalance;
await send('applied the pending balance', [
  buildApplyPendingBalance({
    token: destination,
    authority: payer,
    expectedPendingBalanceCreditCounter: destinationBefore.expectedPendingBalanceCreditCounter,
    newDecryptableAvailableBalance: encryptBalance(keys, newAvailable),
  }),
]);

// ---------------------------------------------------------------------------
// 6 · Report what actually landed
// ---------------------------------------------------------------------------

step('6', 'Read the result back and decrypt it locally');

const finalInfo = await rpc.getAccountInfo(destination, { encoding: 'base64' }).send();
if (!finalInfo.value) throw new Error('the destination vanished after the apply');
const decodedFinal = tokenDecoder.decode(Buffer.from(finalInfo.value.data[0], 'base64'));
const destinationAfter = decryptConfidentialTransferBalance({
  tokenAccount: decodedFinal,
  elgamalSecretKey: sourceElgamalKeypair.secret(),
  aesKey,
});

if (destinationAfter.availableBalance !== newAvailable || destinationAfter.pendingBalance !== 0n) {
  stop(
    'the destination did not settle as expected',
    `available ${destinationAfter.availableBalance}, pending ${destinationAfter.pendingBalance}`,
  );
} else {
  ok(
    'the destination settled',
    `available ${destinationAfter.availableBalance}, pending ${destinationAfter.pendingBalance}`,
  );
}

if (failed === 0) {
  // Recorded only on a clean run, so a partial attempt does not claim a
  // destination it never funded.
  await saveJSON(RUNS_PATH, {
    runs: [
      ...priorRuns.runs,
      {
        destination: String(destination),
        amount: String(AMOUNT),
        signature: transferSignature,
        at: new Date().toISOString(),
      },
    ],
  } satisfies GoLiveRuns);
  ok('the run was recorded', relative(RUNS_PATH));
}

// The explorer wants a cluster *name*; the offer carries a CAIP-2 genesis hash.
// The endpoint this run actually used is the least ambiguous way to recover it.
const explorerCluster = /devnet|testnet|mainnet/.test(rpcUrl)
  ? rpcUrl.includes('devnet')
    ? 'devnet'
    : rpcUrl.includes('testnet')
      ? 'testnet'
      : 'mainnet-beta'
  : options.network.includes('devnet')
    ? 'devnet'
    : options.network.includes('testnet')
      ? 'testnet'
      : 'mainnet-beta';

process.stdout.write(
  [
    '',
    'Veil — live on chain',
    '',
    table([
      ['mint', String(mint)],
      ['payer', String(payer.address)],
      ['source', String(source.address)],
      ['destination', String(destination)],
      ['amount', `${AMOUNT} atomic units, never in the clear`],
      ['proofs', '3 per transfer, generated locally'],
      ['landed', `${destinationAfter.availableBalance} atomic units, decrypted locally`],
    ]),
    '',
    'The amount moved between two accounts without appearing in the clear.',
    'The only place it was ever legible was this process, which held the keys.',
    '',
    failed === 0
      ? `Look it up: https://explorer.solana.com/address/${destination}?cluster=${explorerCluster}`
      : `${failed} check(s) failed.`,
    '',
  ].join('\n'),
);

process.exit(failed === 0 ? 0 : 1);
